CREATE TABLE roles(
                      id          int  not null primary key,
                      description text not null

);
INSERT INTO roles (id, description)
VALUES (0,'ROLE_ADMIN');
INSERT INTO roles (id, description)
VALUES (1,'ROLE_USER');


CREATE TABLE degrees(
                        id          int  not null primary key,
                        description text not null
);
INSERT INTO degrees(id, description)
VALUES (0, 'LLB');
INSERT INTO degrees(id, description)
VALUES (1, 'JD');
INSERT INTO degrees(id, description)
VALUES (2, 'LLM');
INSERT INTO degrees(id, description)
VALUES (3, 'PhD');
INSERT INTO degrees(id, description)
VALUES (4, 'SJD');

CREATE TABLE branches_of_law(
                                id          int  not null primary key,
                                description text not null
);
INSERT INTO branches_of_law (id, description)
VALUES (0, 'CIVIL');
INSERT INTO branches_of_law (id, description)
VALUES (1, 'CRIMINAL');
INSERT INTO branches_of_law (id, description)
VALUES (2, 'TAX');
INSERT INTO branches_of_law (id, description)
VALUES (3, 'BANK');
INSERT INTO branches_of_law (id, description)
VALUES (4, 'FAMILY');

CREATE TABLE locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address   TEXT,
    latitude  FLOAT,
    longitude FLOAT,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE prices
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consultation_price            FLOAT                                   NOT NULL,
    document_revue_price          FLOAT,
    representation_in_court_price FLOAT,
    all_in_price                  FLOAT,
    CONSTRAINT pk_prices PRIMARY KEY (id)
);


CREATE TABLE lawyers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lawyer_email    VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    phone_number    VARCHAR(255),
    degree          INTEGER references degrees(id),
    work_experience TEXT,
    branch_of_law   INTEGER references branches_of_law(id),
    lawyer_id       BIGINT,
    location_id     BIGINT,
    CONSTRAINT pk_lawyers PRIMARY KEY (id)
);

ALTER TABLE lawyers
    ADD CONSTRAINT uc_lawyers_lawyer_email UNIQUE (lawyer_email);

ALTER TABLE lawyers
    ADD CONSTRAINT FK_LAWYERS_ON_LAWYER FOREIGN KEY (lawyer_id) REFERENCES prices (id);

ALTER TABLE lawyers
    ADD CONSTRAINT FK_LAWYERS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

CREATE TABLE costumers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    role        INTEGER                                 NOT NULL references roles(id),
    location_id BIGINT,
    CONSTRAINT pk_costumers PRIMARY KEY (id)
);

ALTER TABLE costumers
    ADD CONSTRAINT uc_costumers_email UNIQUE (email);


ALTER TABLE costumers
    ADD CONSTRAINT FK_COSTUMERS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);
CREATE TABLE case_descriptions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch_of_law INTEGER references branches_of_law(id),
    description   TEXT,
    costumer_id   BIGINT,
    CONSTRAINT pk_case_descriptions PRIMARY KEY (id)
);
ALTER TABLE case_descriptions
    ADD CONSTRAINT FK_CASE_DESCRIPTIONS_ON_COSTUMER FOREIGN KEY (costumer_id) REFERENCES costumers (id) on DELETE cascade ;
ALTER TABLE degrees
    ADD CONSTRAINT id UNIQUE (id);

